### ISSUE TITLE
Updates and detailed/modified validation

### ISSUE THREAD

**Issue by dantman** [koblas/ibankit-js#15]
[Current version](https://www.swift.com/standards/data-standards/iban-international-bank-account-number) of the IBAN registry appears to be Version 88. Will the library be updated?

Could the detailed validation parts of ibanUtils be made part of the external API? I'd like to basically repeat the steps in `validate()` but tweak them to skip country validation so XX and newly added countries don't have validation errors.

**Comment by koblas** [comment]
Just to make sure I understand your issue, I see two things:

1. Please make sure the IBANkit is updated to fully support version 88 of the IBAN spec.

2. You would like to validate IBAN checksums ignoring any BBAN or Country Validation (BBAN validation requires country validation)   `validate(iban: string, options?: { allowUnknownCountries: boolean })` or some similar approach.

**Comment by dantman** [comment]
1. Yes, just to confirm the library is being maintained, considering the library it's a drop in replacement for appears to be unmaintained.
2. Pretty much (of course validating BBANs for known countries). Options would work, so would exposing `intlUtils` so I can just make the same calls as `validate()` does and tweak them. The client I'm working for uses XX with a set format for internal accounts and doesn't want invalid countries to be considered errors on the client side so they can easily add custom routing e.g. for American accounts with US.

**Comment by koblas** [comment]
Let me think about this for a little bit, but in general the answer is "yes".

Laughing a little bit here, since I've considered encoding US/CA account numbers in IBANs as well (AU/NZ would be easy but don't deal with them much).

**Comment by koblas** [comment]
Here's an update which should bring it into compliance with version 88, along with add a method that might help you.  Please read through and comment if you have any thoughts.

https://github.com/koblas/ibankit-js/pull/16

For your "country" challenge, one think that is still not working is that you wouldn't be able to say:
  new IBAN("USnnnnnn.....")
  
 And have it work, since the `US` is not a valid IBAN country and/or generate a check digit is also still a little weird.  Will say that you're making me think about how to throw everything out and rebuild a better underlying framework.

**Comment by dantman** [comment]
Thanks for releasing 1.40. However it appears the package contains raw TypeScript instead of the compiled files that the package.json reference.

**Comment by koblas** [comment]
:( Shakes his head in shame...

Updated the build and got interrupted before I double checked it worked...  Fixed, sorry.

**Comment by dantman** [comment]
Getting better. However it appears that when catching the validation errors it's actually not possible to do an instanceof check on them. i.e. When the checksum is invalid I can see the `expected` property, but I cannot know that it's an InvalidCheckDigitException because the error is actually a plain Error and does not inherit from InvalidCheckDigitException.

It appears to be due to this TypeScript change: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#extending-built-ins-like-error-array-and-map-may-no-longer-work

**Comment by koblas** [comment]
Should now be resolved in 1.4.3
