### ISSUE TITLE
dist / webbrowser script

### ISSUE THREAD

**Issue by SanderMuller** [koblas/ibankit-js#17]
I would like to use this in a webbrowser project that doesn't support modules (import/require) yet.

If a drop-in for https://www.npmjs.com/package/iban#in-the-browser could be distributed in this package, I would be very grateful!

**Comment by koblas** [comment]
While I've not tried this in a browser it shouldn't require modules. This was intended to be as portable across environments as possible. 

Is there some reason webpack or parcel is not building it out correctly.

**Comment by SanderMuller** [comment]
Thanks for the quick response!

My project works by concatting JS files (via webpack) instead of exports/imports.

To add iban.js I can simply add `'node_modules/iban/iban.js'` to the list of scripts to be concatted (together with the scrips for my application). 

However, when I do this with ibankit, webpack will break my existing scripts.

`'node_modules/ibankit/lib/iban.js'` or `'node_modules/ibankit/lib/index.js'` generate the following error in the browser: `Uncaught ReferenceError: exports is not defined at iban.ts:118`


`'node_modules/ibankit/src/index.ts'` generates the following error in the browser: Uncaught SyntaxError: Unexpected token 'export'

`'node_modules/ibankit/src/iban.ts'` generatesS the following error in the browser: Uncaught SyntaxError: Cannot use import statement outside a module

**Comment by koblas** [comment]
I believe that adding `@babel/plugin-transform-modules-commonjs` to your web pack plugins should solve this.

**Comment by koblas** [comment]
Any update?  Will close in a few days if I don't hear back.
