### ISSUE TITLE
Error messages using `Object.entries` and `Object.values`

### ISSUE THREAD

**Issue by waldyrious** [koblas/ibankit-js#3]
I have very little experience with TypeScript, so this may be a false alarm, but after I imported ibankit into my project, VSCode is showing me two warnings:

> Property 'entries' does not exist on type 'ObjectConstructor'.

in

https://github.com/koblas/ibankit-js/blob/3ba59db938d2147655f0617823440c7de9be8d5d/src/bbanStructure.ts#L60

and

https://github.com/koblas/ibankit-js/blob/3ba59db938d2147655f0617823440c7de9be8d5d/src/country.ts#L513-L521

as well as

> Property 'values' does not exist on type 'ObjectConstructor'.

in

https://github.com/koblas/ibankit-js/blob/3ba59db938d2147655f0617823440c7de9be8d5d/src/bbanStructure.ts#L876

Is this something misconfigured on my end, or is it a legitimate issue?

**Comment by waldyrious** [comment]
The project I tried this in is not a typescript project, so it doesn't have a `tsconfig.json` file. Should I add one to the project directory even though it's not itself a typescript project?

**Comment by koblas** [comment]
Ugh - just learned something.  TypeScript by default doesn't include the polyfills that are I'm using.

Options:
1) Convince me to write the code without using Object.entries() or Object.values()
2) Import core-js and the or the polyfill of your choice
3) Have me bake into the system a polyfill (still like the idea of 0 external dependencies)

**Comment by waldyrious** [comment]
I don't think Option 2 leads to a good experience in usage of this package. IMO the less friction and manual steps there are, the more likely people are to start and continue using it.

Between options 1 and 3, it ends up being a choice between the neatness of zero-dependencies and the neatness of newer ES syntax -- so it's a subjective choice that you're the most qualified person to make.

I would personally go with the latter (i.e. option 3), especially since the support for older ES syntax can be dropped once its prevalence becomes sufficiently low among JS engines, thus returning the package to the zero-dependencies status. WDYT?

**Comment by koblas** [comment]
Did a bit better -- there is a small compatibility layer in there, still no external dependancies.
