### ISSUE TITLE
v1.6.4 contains the bug returning valid for invalid BIC

### ISSUE THREAD

**Issue by AlexJurik** [koblas/ibankit-js#42]
After upgrading from v1.6.3 to v1.6.4 we started having issues with tests testing `1234US56` BIC validity. Downgrading to v1.6.3 solved the problem.

**Comment by koblas** [comment]
ISO-9362:2022 updated the specifications for BIC to be optional numeric in the first 4 digits, so based on current standards `1234` is a valid BIC prefix.

In retrospect, this should have warranted a 1.6 -> 1.7 bump in version.
