### ISSUE TITLE
Getting bank name and BIC from IBAN

### ISSUE THREAD

**Issue by mmestani** [koblas/ibankit-js#6]
Can we somehow get the Bank name and BIC from IBAN?

**Comment by mmestani** [comment]
@koblas - is this possible?

**Comment by koblas** [comment]
Swift -- The BIC database is a product of the Swift Institue so it cannot be built into this library due to copyright issues.

IBAN -- This would require building a DB from a collection of DBs -- this would be possible, but probably outside the current scope of this project.
